name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Используйте точную версию (не "3.x")

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate  # Linux/Mac
          # venv\Scripts\activate   # Windows (если используется windows-раннер)

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flask pytest  # Или используйте requirements.txt

      - name: Run tests
        run: pytest