name: CI Pipeline
on: [push, pull_request]  # Запуск при пуше или PR

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Run pylint
        run: pylint app.py

      - name: Run mypy
        run: mypy app.py --strict